---
swagger: "2.0"
info:
  description: "Sympt SENG3011 Promed API"
  version: "1.0.0"
  title: "Sympt Promed API"
  contact:
    email: "sympt.3011@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.sympt-3011.herokuapp.com"
host: "virtserver.swaggerhub.com"
basePath: "/sympt-30117/symptAPI/1.0.0"
tags:
- name: "developers"
  description: "Operations available to regular developers"
schemes:
- "https"
paths:
  /proMed:
    get:
      tags:
      - "developers"
      summary: "searches database"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ ProMed disease reports in the system\n"
      operationId: "searchProMedDIseaseReports"
      produces:
      - "application/json"
      parameters:
      - name: "startDate"
        in: "query"
        description: "pass a required start date"
        required: true
        type: "string"
      - name: "endDate"
        in: "query"
        description: "pass a required end date"
        required: true
        type: "string"
      - name: "location"
        in: "query"
        description: "search disease reports by a location name"
        required: true
        type: "string"
      - name: "keyterms"
        in: "query"
        description: "a comma separated list of all the key terms"
        required: false
        type: "string"
      - name: "token"
        in: "query"
        description: "authorisation token"
        required: true
        type: "string"
      responses:
        "200":
          description: "disease reports matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/proMedItem"
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
definitions:
  proMedItem:
    type: "object"
    required:
    - "date_of_publication"
    - "diseases"
    - "headline"
    - "main_text"
    - "reports"
    - "syndromes"
    - "url"
    properties:
      url:
        type: "string"
        example: "https://promedmail.org/promed-post/?id=6943858"
      date_of_publication:
        type: "string"
        example: "2020-02-01 23:02:03"
      headline:
        type: "string"
        example: "Novel coronavirus (28): China (HU) animal reservoir"
      main_text:
        type: "string"
        example: "NOVEL CORONAVIRUS (28): CHINA (HUBEI) ANIMAL RESERVOIR ******************************************************\
          \ A ProMED-mail post  http://www.promedmail.org  ProMED-mail is a program\
          \ of the International Society for Infectious Diseases  http://www.isid.org\
          \  In this posting: [1] Measures to regulate the trade and maintenance of\
          \ wild animals in China [2] Virus detection in environmental samples from\
          \ the seafood market [3] Initial epidemiology, public announcement, 31 Dec\
          \ 2019 ****** [1] Measures to regulate the trade and maintenance of wild\
          \ animals in China Date: Fri 31 Jan 2020 Source: Xinhuanet News [in Chinese,\
          \ machine trans., abridged, edited]  http://www.xinhuanet.com/politics/2020-01/31/c_1125515239.htm\
          \  On 26 Jan 2020, the China Centers for Disease Control and Prevention\
          \ announced that the new coronavirus was detected in environmental samples\
          \ from the South China Seafood Market in Wuhan [see item 2]. The virus originated\
          \ from wild animals sold in the seafood market. For this reason, the State\
          \ General Administration of Market Supervision, the Ministry of Agriculture\
          \ and Rural Affairs, and the National Forestry and Grassland Bureau jointly\
          \ issued a public announcement on the 26th that from now on until the end\
          \ of the national epidemic, wild animal trading activities are prohibited\
          \ to cut off the source and transmission of the virus."
      reports:
        $ref: "#/definitions/Report"
      diseases:
        type: "array"
        items:
          type: "string"
          example: "Coronavirus"
      syndromes:
        type: "array"
        items:
          type: "string"
          example: "Fever"
    example:
      reports:
        event_date: "2020-01-03 xx:xx:xx to 2020-01-15"
        locations:
          country: "China"
          location: "Wuhan"
      date_of_publication: "2020-02-01 23:02:03"
      diseases:
      - "Coronavirus"
      - "Coronavirus"
      main_text: "NOVEL CORONAVIRUS (28): CHINA (HUBEI) ANIMAL RESERVOIR ******************************************************\
        \ A ProMED-mail post  http://www.promedmail.org  ProMED-mail is a program\
        \ of the International Society for Infectious Diseases  http://www.isid.org\
        \  In this posting: [1] Measures to regulate the trade and maintenance of\
        \ wild animals in China [2] Virus detection in environmental samples from\
        \ the seafood market [3] Initial epidemiology, public announcement, 31 Dec\
        \ 2019 ****** [1] Measures to regulate the trade and maintenance of wild animals\
        \ in China Date: Fri 31 Jan 2020 Source: Xinhuanet News [in Chinese, machine\
        \ trans., abridged, edited]  http://www.xinhuanet.com/politics/2020-01/31/c_1125515239.htm\
        \  On 26 Jan 2020, the China Centers for Disease Control and Prevention announced\
        \ that the new coronavirus was detected in environmental samples from the\
        \ South China Seafood Market in Wuhan [see item 2]. The virus originated from\
        \ wild animals sold in the seafood market. For this reason, the State General\
        \ Administration of Market Supervision, the Ministry of Agriculture and Rural\
        \ Affairs, and the National Forestry and Grassland Bureau jointly issued a\
        \ public announcement on the 26th that from now on until the end of the national\
        \ epidemic, wild animal trading activities are prohibited to cut off the source\
        \ and transmission of the virus."
      syndromes:
      - "Fever"
      - "Fever"
      headline: "Novel coronavirus (28): China (HU) animal reservoir"
      url: "https://promedmail.org/promed-post/?id=6943858"
  Report:
    required:
    - "event_date"
    properties:
      event_date:
        type: "string"
        example: "2020-01-03 xx:xx:xx to 2020-01-15"
      locations:
        $ref: "#/definitions/Location"
    example:
      event_date: "2020-01-03 xx:xx:xx to 2020-01-15"
      locations:
        country: "China"
        location: "Wuhan"
  Location:
    required:
    - "country"
    - "location"
    properties:
      country:
        type: "string"
        example: "China"
      location:
        type: "string"
        example: "Wuhan"
    example:
      country: "China"
      location: "Wuhan"
