---
swagger: "2.0"
info:
  description: "Sympt API - SENG3011\n \
  \ API returns disease reports according to search criteria found from promedmail.org/"
  version: "1.0.0"
  title: "Sympt API"
  contact:
    email: "sympty.3011@gmail.com"
tags:
- name: "developers"
  description: "Operations available to developers"
schemes:
- "https"
- "http"
paths:
  /articles/:
    get:
      tags:
      - "developers"
      summary: "Searches database for articles according to search criterias."
      description: "By passing in the appropriate search criteria, you can search for available \
        \ disease reports in the database.\n A scrape of articles will be triggered if there are less than 5 results in the database."
      operationId: "searchDiseaseReports"
      produces:
      - "application/json"
      parameters:
      # - name: auth
      #   in: header
      #   description: an authorization header
      #   required: true
      #   type: string
      - name: "startdate"
        in: "query"
        description: "The start date to search for articles published after this date (ISO time string format).\n e.g. 2019-06-02T00:00:00"
        required: true
        type: "string"
      - name: "enddate"
        in: "query"
        description: "The end date to search for articles published before this date (ISO time string format). \n e.g. 2020-02-02T00:00:00"
        required: true
        type: "string"
      - name: "location"
        in: "query"
        description: "Search disease reports relevent to a location. \n e.g. china"
        required: false
        type: "string"
        default: "china"
      - name: "keyterms"
        in: "query"
        description: "A comma separated list of key terms related to diseases or events. \n e.g. coronavirus,ebola"
        required: false
        type: "string"
        default: "coronavirus"
      - name: "count"
        in: "query"
        description: "The limit of articles to receive, between 0 and 10. If not set, or set to 0, the API will return all articles matching other criteria."
        required: false
        type: "number"
        default: 5
      - name: "page"
        in: "query"
        description: "Fetch articles from an indicated page, starting from 0; each page contains 'count' no. of articles. Requires count to be set."
        required: false
        type: "number"
        default: 0
      responses:
        "200":
          description: "Disease reports matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
        "400":
          description: "Bad input parameter"
        "500":
          description: "Insufficient articles"
      x-swagger-router-controller: "Developers"


definitions:
  Article:
    type: "object"
    required:
    - "date_of_publication"
    - "headline"
    - "main_text"
    - "reports"
    - "url"
    properties:
      url:
        type: "string"
        example: "https://promedmail.org/promed-post/?id=6943858"
      date_of_publication:
        type: "string"
        example: "2020-02-01 23:02:03"
      headline:
        type: "string"
        example: "Novel coronavirus (28): China (HU) animal reservoir"
      main_text:
        type: "string"
        example: "On 26 Jan 2020, the China Centers for Disease Control and Prevention announced \
        \ that the new coronavirus was detected in environmental samples from the\
        \ South China Seafood Market in Wuhan [see item 2]. The virus originated from\
        \ wild animals sold in the seafood market. For this reason, the State General\
        \ Administration of Market Supervision, the Ministry of Agriculture and Rural\
        \ Affairs, and the National Forestry and Grassland Bureau jointly issued a\
        \ public announcement on the 26th that from now on until the end of the national\
        \ epidemic, wild animal trading activities are prohibited to cut off the source\
        \ and transmission of the virus."
      reports:
        type: "array"
        items:
          $ref: "#/definitions/Report"
      
  Report:
    required:
    - "event_date"
    - "locations"
    - "diseases"
    - "syndromes"
    properties:
      event_date:
        type: "string"
        example: "2020-01-03 xx:xx:xx to 2020-01-15"
      locations:
        $ref: "#/definitions/Location"
      diseases:
        type: "array"
        items:
          type: "string"
          example: "Coronavirus"
      syndromes:
        type: "array"
        items:
          type: "string"
          example: "Fever"
  Location:
    required:
    - "country"
    - "location"
    properties:
      country:
        type: "string"
        example: "China"
      location:
        type: "string"
        example: "Wuhan"
host: sympt-server.herokuapp.com
basePath: /