---
swagger: "2.0"
info:
  description: "Sympt API - SENG3011\n \
  \ API returns disease reports according to search criteria found from promedmail.org/"
  version: "1.0.0"
  title: "Sympt API"
  contact:
    email: "sympt.3011@gmail.com"
tags:
- name: "developers"
  description: "Operations available to developers"
schemes:
- "https"
paths:
  /articles/:
    get:
      tags:
      - "developers"
      summary: "Searches database for articles according to search criterias."
      description: "By passing in the appropriate options, you can search for available \
        \ disease reports in the database.\n A scrape of disease websites will be triggered if there are no results in database."
      operationId: "searchDiseaseReports"
      produces:
      - "application/json"
      parameters:
      # - name: auth
      #   in: header
      #   description: an authorization header
      #   required: true
      #   type: string
      - name: "startdate"
        in: "query"
        description: "The start date to search for articles published after this date (ISO time string format).\n Example: 2000-02-02T00:00:00"
        required: true
        type: "string"
      - name: "enddate"
        in: "query"
        description: "The end date to search for articles published before this date (ISO time string format). \n Example: 2020-02-02T00:00:00"
        required: true
        type: "string"
      - name: "location"
        in: "query"
        description: "Search disease reports relavent to a location. \n Example: china"
        required: true
        type: "string"
      - name: "keyterms"
        in: "query"
        description: "A comma separated list of key terms related to diseases or events."
        required: false
        type: "string"
        default: "coronavirus"
      - name: "count"
        in: "query"
        description: "Add a limit of articles to receive. Fetching articles beyond what is available in the database will automatically trigger the web scraper."
        required: false
        type: "number"
        default: 10
      responses:
        "200":
          description: "Disease reports matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
        "400":
          description: "Bad input parameter"
        "500":
          description: "Insufficient articles"
      x-swagger-router-controller: "Developers"

  /articles-force/:
    get:
      tags:
      - "developers"
      summary: "Force scrape of web sources for articles according to search criterias, and returns results."
      description: "Will force a rescrape of web sources and will search on provided criteria."
      operationId: "forceScrapeDiseaseReports"
      produces:
      - "application/json"
      parameters:
      # - name: auth
      #   in: header
      #   description: an authorization header
      #   required: true
      #   type: string
      - name: "startdate"
        in: "query"
        description: "The start date to search for articles published after this date (ISO time string format).\n Example: 2000-02-02T00:00:00"
        required: true
        type: "string"
      - name: "enddate"
        in: "query"
        description: "The end date to search for articles published before this date (ISO time string format). \n Example: 2020-02-02T00:00:00"
        required: true
        type: "string"
      - name: "location"
        in: "query"
        description: "Search disease reports by a location name. \n Example: china"
        required: true
        type: "string"
      - name: "keyterms"
        in: "query"
        description: "A comma separated list of key terms related to diseases or events."
        required: false
        type: "string"
        default: "coronavirus"
      responses:
        "200":
          description: "Disease reports matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
        "400":
          description: "Bad input parameter"
        "500":
          description: "Insufficient articles"
      x-swagger-router-controller: "Developers"
  
definitions:
  Article:
    type: "object"
    required:
    - "date_of_publication"
    - "headline"
    - "main_text"
    - "reports"
    - "url"
    properties:
      url:
        type: "string"
      date_of_publication:
        type: "string"
      headline:
        type: "string"
      main_text:
        type: "string"
      reports:
        $ref: "#/definitions/Report"
      
    example:
      reports:
        event_date: "2020-01-03 xx:xx:xx to 2020-01-15"
        locations:
          country: "China"
          location: "Wuhan"
        date_of_publication: "2020-02-01 23:02:03"
        diseases:
        - "Coronavirus"
        syndromes:
        - "Fever"
      main_text: "NOVEL CORONAVIRUS (28): CHINA (HUBEI) ANIMAL RESERVOIR ******************************************************\
        \ A ProMED-mail post  http://www.promedmail.org  ProMED-mail is a program\
        \ of the International Society for Infectious Diseases  http://www.isid.org\
        \  In this posting: [1] Measures to regulate the trade and maintenance of\
        \ wild animals in China [2] Virus detection in environmental samples from\
        \ the seafood market [3] Initial epidemiology, public announcement, 31 Dec\
        \ 2019 ****** [1] Measures to regulate the trade and maintenance of wild animals\
        \ in China Date: Fri 31 Jan 2020 Source: Xinhuanet News [in Chinese, machine\
        \ trans., abridged, edited]  http://www.xinhuanet.com/politics/2020-01/31/c_1125515239.htm\
        \  On 26 Jan 2020, the China Centers for Disease Control and Prevention announced\
        \ that the new coronavirus was detected in environmental samples from the\
        \ South China Seafood Market in Wuhan [see item 2]. The virus originated from\
        \ wild animals sold in the seafood market. For this reason, the State General\
        \ Administration of Market Supervision, the Ministry of Agriculture and Rural\
        \ Affairs, and the National Forestry and Grassland Bureau jointly issued a\
        \ public announcement on the 26th that from now on until the end of the national\
        \ epidemic, wild animal trading activities are prohibited to cut off the source\
        \ and transmission of the virus."
  
      headline: "Novel coronavirus (28): China (HU) animal reservoir"
      url: "https://promedmail.org/promed-post/?id=6943858"
  Report:
    required:
    - "event_date"
    - "locations"
    - "diseases"
    - "syndromes"
    properties:
      event_date:
        type: "string"
        example: "2020-01-03 xx:xx:xx to 2020-01-15"
      locations:
        $ref: "#/definitions/Location"
      diseases:
        type: "array"
        items:
          type: "string"
          example: "Coronavirus"
      syndromes:
        type: "array"
        items:
          type: "string"
          example: "Fever"
    example:
      event_date: "2020-01-03 xx:xx:xx to 2020-01-15"
      locations:
        country: "China"
        location: "Wuhan"
  Location:
    required:
    - "country"
    - "location"
    properties:
      country:
        type: "string"
        example: "China"
      location:
        type: "string"
        example: "Wuhan"
    example:
      country: "China"
      location: "Wuhan"
# host: sympt-server.herokuapp.com
# basePath: /
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /sympt-30117/symptAPI/1.0.0