export const dummyNewsData = {
  status: "ok",
  totalResults: 4697,
  articles: [
    {
      source: {
        id: "politico",
        name: "Politico",
      },
      author: "By Anna Palmer and Jake Sherman",
      title: "POLITICO Playbook: Trump’s nationalism has gone domestic",
      description: "And the president extends social distancing guidelines through the end of the month.",
      url: "https://www.politico.com/newsletters/playbook/2020/03/30/trumps-nationalism-has-gone-domestic-488745",
      urlToImage: "https://static.politico.com/0b/18/cc504b1e45b4aa56ba1ac5bce1c3/gettyimages-1208533812.jpg",
      publishedAt: "2020-03-30T09:45:12Z",
      content: "President Donald Trumps worldview that nations alone, in their own self-interest, act to protect themselves is playing out now among different U.S. states. | Pete Marovich-Pool/Getty Images\r\nDRIVING THE DAY\r\nTRUMPS NATIONALISM HAS GONE DOMESTIC: President DON… [+20154 chars]",
    },
    {
      source: {
        id: null,
        name: "Bbc.com",
      },
      author: "https://www.facebook.com/bbcnews",
      title: "Alan Merrill: I Love Rock 'N' Roll songwriter dies of coronavirus",
      description: "Alan Merrill co-wrote and sang the glam rock classic before Joan Jett made it famous.",
      url: "https://www.bbc.com/news/entertainment-arts-52089768",
      urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/17CE3/production/_111470579_gettyimages-703911041small.jpg",
      publishedAt: "2020-03-30T09:18:57Z",
      content: "Image copyrightGetty ImagesImage caption\r\n The singer had a long and varied career in music, with bands in Japan, the UK and the US\r\nThe co-writer and original singer of I Love Rock 'N' Roll, Alan Merrill, has died after contracting coronavirus.\r\nHis daughter… [+3766 chars]",
    },
    {
      source: {
        id: "cbs-news",
        name: "CBS News",
      },
      author: "CBS News",
      title: "Coronavirus updates: Trump extends shutdown, Fauci warns 200k could die",
      description: "President says U.S. likely still 2 weeks from COVID-19 \"peak\" as New York governor warns it's spreading \"like fire through dry grass\" in nursing care homes.",
      url: "https://www.cbsnews.com/live-updates/coronavirus-disease-covid-19-latest-news-2020-03-30/",
      urlToImage: "https://cbsnews2.cbsistatic.com/hub/i/r/2020/03/30/ec807c01-2119-4e4f-b40c-a04198b7d765/thumbnail/1200x630/413ef5cbf7fac25b92103f1ddd1dcbb3/coronavirus-nursing-home.jpg",
      publishedAt: "2020-03-30T09:17:03Z",
      content: "The coronavirus pandemic has deeply affected America's farmers, who were already facing financial hardships, worsened by a trade war and labor shortages.\r\nIn the heart of Dallas, Bonton Farms planted roots in an often-forgotten neighborhood that's long been a… [+740 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Reuters Editorial",
      title: "George Soros gives 1 million euros to Budapest's coronavirus fight",
      description: "George Soros, the 89-year-old billionaire financier, said on Monday his Open Society Foundations would contribute 1 million euros to Budapest's fight against coronavirus.",
      url: "https://in.reuters.com/article/us-health-coronavirus-soros-hungary-idINKBN21H14Y",
      urlToImage: "https://s4.reutersmedia.net/resources_v2/images/rcom-default.png",
      publishedAt: "2020-03-30T09:16:05Z",
      content: "LONDON (Reuters) - George Soros, the 89-year-old billionaire financier, said on Monday his Open Society Foundations would contribute 1 million euros to Budapest’s fight against coronavirus. \r\n“The COVID-19 pandemic knows no boundaries, not between countries, … [+491 chars]",
    },
    {
      source: {
        id: "the-washington-post",
        name: "The Washington Post",
      },
      author: "Associated Press",
      title: "Mercedes F1 team helps to develop breathing aid in pandemic",
      description: "Formula One team Mercedes has helped to develop a breathing aid that could keep coronavirus patients out of intensive care and ease some pressure on Britain's strained health service",
      url: "https://www.washingtonpost.com/world/europe/mercedes-f1-team-helps-to-develop-breathing-aid-in-pandemic/2020/03/30/d8182a7a-7266-11ea-ad9b-254ec99993bc_story.html",
      urlToImage: "",
      publishedAt: "2020-03-30T09:14:23Z",
      content: "The device, known as continuous positive airway pressure, has been used extensively in hospitals in Italy and China to deliver oxygen to the lungs of coronavirus patients during the pandemic.\r\nUCL said the adapted devices have been recommended for use in Brit… [+1795 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Bozorgmehr Sharafedin",
      title: "Oil hits 18-year low as lockdowns diminish demand",
      description: "Crude oil fell sharply on Monday, with U.S. crude briefly dropping below $20 and Brent hitting its lowest level in 18 years, on heightened fears that the global coronavirus shutdown could last months and demand for fuel could evaporate further.",
      url: "https://www.reuters.com/article/us-global-oil-idUSKBN21G0XR",
      urlToImage: "https://s1.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510093374&w=1200&r=LYNXMPEG2S0L2",
      publishedAt: "2020-03-30T09:12:02Z",
      content: "LONDON (Reuters) - Crude oil fell sharply on Monday, with U.S. crude briefly dropping below $20 and Brent hitting its lowest level in 18 years, on heightened fears that the global coronavirus shutdown could last months and demand for fuel could evaporate furt… [+2902 chars]",
    },
    {
      source: {
        id: "the-washington-post",
        name: "The Washington Post",
      },
      author: "Farai Mutsaka, AP",
      title: "In Zimbabwe, 'you win coronavirus or you win starvation'",
      description: "As Zimbabwe enters lockdown, people in the economically shattered country are forced to choose between daily survival and measures to protect themselves from the coronavirus",
      url: "https://www.washingtonpost.com/world/africa/in-zimbabwe-you-win-coronavirus-or-you-win-starvation/2020/03/30/dc185b5a-7265-11ea-ad9b-254ec99993bc_story.html",
      urlToImage: "https://www.washingtonpost.com/resizer/2CjPNwqvXHPS_2RpuRTKY-p3eVo=/1484x0/www.washingtonpost.com/pb/resources/img/twp-social-share.png",
      publishedAt: "2020-03-30T09:07:20Z",
      content: "HARARE, Zimbabwe We are already ruined. What more harm can coronavirus do? Irene Kampira asked as she sorted secondhand clothes at a bustling market in a poor suburb of Zimbabwes capital, Harare.\r\nPeople in one of the worlds most devastated nations are choosi… [+4612 chars]",
    },
    {
      source: {
        id: "politico",
        name: "Politico",
      },
      author: "Sam Sutton",
      title: "Forget Washington — corporate America is focused on governors right now",
      description: "States’ assertion of decision-making power over commerce is nearly unprecedented — and it hasn’t been pretty, from the viewpoint of many businesses.",
      url: "https://www.politico.com/states/california/story/2020/03/30/forget-washington-corporate-america-is-focused-on-governors-right-now-1269488",
      urlToImage: "https://static.politico.com/aa/b0/7a6750c6432baf048ea2ebc320be/ap-nj-testing-900.jpg",
      publishedAt: "2020-03-30T09:02:36Z",
      content: "People in protective gear administer tests for Covid-19 at a drive-through testing center in Paramus, N.J. | Seth Wenig/AP Photo\r\nNEW YORK When Goldman Sachs directed more than 12,000 employees in the New York City metro area to work from home two weeks ago, … [+5900 chars]",
    },
    {
      source: {
        id: "politico",
        name: "Politico",
      },
      author: "Jennifer Nuzzo",
      title: "Opinion | A Game Plan to End Social Distancing",
      description: "If we’re serious about controlling the crisis, here’s what it will take—and who needs to step up, from the Pentagon to the Peace Corps.",
      url: "https://www.politico.com/news/agenda/2020/03/30/social-distancing-game-plan-154915",
      urlToImage: "https://static.politico.com/b4/4e/8b67c51b413381f54dbe46bbce1a/20200329-social-dostancing-gty-773.jpg",
      publishedAt: "2020-03-30T09:00:10Z",
      content: "So what needs to happen next? And who is supposed to help us get there? To spin up a new nationwide surveillance program in real time is a huge lift and will require a coordinated game plan from different agencies, governments and leadersand even the private … [+7801 chars]",
    },
    {
      source: {
        id: "the-washington-post",
        name: "The Washington Post",
      },
      author: "Suparna Chaudhry, Shubha Kamala Prasad",
      title: "How India plans to put 1.3 billion people on a coronavirus lockdown",
      description: "Can India get that many people to stay home?",
      url: "https://www.washingtonpost.com/politics/2020/03/30/how-india-plans-put-13-billion-people-coronavirus-lockdown/",
      urlToImage: "https://www.washingtonpost.com/resizer/cTcY1Rd01Qk4cY-bQ3zfmIKx9ww=/1440x0/smart/arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/Q54522TRYII6VLM3EVHMTGMTXQ.jpg",
      publishedAt: "2020-03-30T09:00:00Z",
      content: "Heres what you need to know about Indias preparedness for weathering this pandemic, and the potential effects of the government lockdown.\r\n1. What is Indias covid-19 situation? \r\nIndia had more than 1,000 coronavirus cases as of Sunday, and 27 deaths. The gov… [+6858 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Reuters Editorial",
      title: "Greece pumps more financial aid in economy to deal with coronavirus",
      description: "Greece announced new tax breaks and economic assistance to thousands of businesses and workers on Monday to buffer its economy from a national lockdown triggered by the coronavirus pandemic.",
      url: "https://www.reuters.com/article/us-health-coronavirus-greece-economy-idUSKBN21H112",
      urlToImage: "https://s1.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510087946&w=1200&r=LYNXMPEG2T0O2",
      publishedAt: "2020-03-30T08:53:42Z",
      content: "ATHENS (Reuters) - Greece announced new tax breaks and economic assistance to thousands of businesses and workers on Monday to buffer its economy from a national lockdown triggered by the coronavirus pandemic. \r\nGreece’s economy is expected to contract by 3 p… [+1705 chars]",
    },
    {
      source: {
        id: "the-washington-post",
        name: "The Washington Post",
      },
      author: "Associated Press",
      title: "German cruise passengers head home, 41 remain in Australia",
      description: "More than 800 cruise ship passengers and crew are heading home to Germany on chartered flights while 41 others infected with the coronavirus have been admitted to an Australian hospital after an argument over where they should be treated among local medical p…",
      url: "https://www.washingtonpost.com/world/german-cruise-passengers-head-home-41-remain-in-australia/2020/03/30/ccaf8200-7261-11ea-ad9b-254ec99993bc_story.html",
      urlToImage: "",
      publishedAt: "2020-03-30T08:38:16Z",
      content: "This humanitarian hospital care will be provided in one of the states premier facilities, which is fully prepared for and is already treating COVID-19 patients, Federal Health Minister Greg Hunt said in a statement Monday.\r\nWestern Australia state Premier Mar… [+1530 chars]",
    },
    {
      source: {
        id: "politico",
        name: "Politico",
      },
      author: "By Tim Alberta",
      title: "Fear in Bulk",
      description: "On the edge of the outbreak, the shelves are almost bare and the dread seems inexhaustible.",
      url: "https://www.politico.com/news/magazine/2020/03/30/letter-to-washington-coronavirus-panic-buying-152314",
      urlToImage: "https://static.politico.com/68/30/f884c4654817aa318df59f0d8db1/lede-art-michigan-override-white.jpg",
      publishedAt: "2020-03-30T08:30:44Z",
      content: "Thats the best way I can describe the feeling inside Sams Club last week.\r\nThe unusually empty parking lot of the Sams Club in Ypsilanti. | Tim Alberta/POLITICO\r\nOn the day I visited the storeWednesday, March 25Michigan had the fifth-most cases of Covid-19, t… [+8179 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Guy Faulconbridge",
      title: "UK epidemic is slowing and antibody test could be ready in days, top epidemiologist says",
      description: "The coronavirus epidemic in the United Kingdom is showing signs of slowing and antibody tests could be ready in days, Neil Ferguson, a professor of mathematical biology at Imperial College London, said on Monday.",
      url: "https://uk.reuters.com/article/us-health-coronavirus-britain-epidemic-idUKKBN21H0SA",
      urlToImage: "https://s4.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510059984&w=1200&r=LYNXMPEG2T0IU",
      publishedAt: "2020-03-30T07:59:34Z",
      content: "LONDON (Reuters) - The coronavirus epidemic in the United Kingdom is showing signs of slowing and antibody tests could be ready in days, Neil Ferguson, a professor of mathematical biology at Imperial College London, said on Monday. \r\n“We think the epidemic is… [+1849 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Reuters Editorial",
      title: "Indonesia president plans stricter rules on mobility, social distancing",
      description: "Indonesian President Joko Widodo said on Monday he plans to impose stricter limits on mobility between regions and also to implement a large-scale policy of social distancing to help curb the spread of coronavirus.",
      url: "https://www.reuters.com/article/us-health-coronavirus-indonesia-idUSKBN21H0TM",
      urlToImage: "https://s4.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510067018&w=1200&r=LYNXMPEG2T0KS",
      publishedAt: "2020-03-30T07:48:32Z",
      content: "JAKARTA (Reuters) - Indonesian President Joko Widodo said on Monday he plans to impose stricter limits on mobility between regions and also to implement a large-scale policy of social distancing to help curb the spread of coronavirus. \r\n“In implementing the p… [+462 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Tangi Salaün",
      title: "Special Report: Five days of worship that set a virus time bomb in France",
      description: "From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: \"We're going to celebrate the Lord! Are you feeling the joy tonight?\"",
      url: "https://ca.reuters.com/article/topNews/idCAKBN21H0Q2",
      urlToImage: "https://s3.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510052791&w=1200&r=LYNXMPEG2T0EJ",
      publishedAt: "2020-03-30T07:41:47Z",
      content: "PARIS (Reuters) - From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: “We’re going to celebrate the Lord! Are you feeling the joy tonight?” \r\n“Yes!” shouted the hundreds gathered at the C… [+13011 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Reuters Editorial",
      title: "Indonesia president plans stricter rules on mobility, social distancing",
      description: "Indonesian President Joko Widodo said on Monday he plans to impose stricter limits on mobility between regions and also to implement a large-scale policy of social distancing to help curb the spread of coronavirus.",
      url: "https://www.reuters.com/article/health-coronavirus-indonesia-idUSJ9N29R01A",
      urlToImage: "https://s4.reutersmedia.net/resources_v2/images/rcom-default.png",
      publishedAt: "2020-03-30T07:27:12Z",
      content: "JAKARTA, March 30 (Reuters) - Indonesian President Joko Widodo said on Monday he plans to impose stricter limits on mobility between regions and also to implement a large-scale policy of social distancing to help curb the spread of coronavirus. \r\n“In implemen… [+471 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Reuters Editorial",
      title: "BRIEF-Franchise Brands Says Trading In Near Term Likely Impacted By Pandemic - Reuters",
      description: "BRIEF-Franchise Brands Says Trading In Near Term Likely Impacted By Pandemic Reuters",
      url: "https://www.reuters.com/article/brief-franchise-brands-says-trading-in-n-idUSFWN2BM02P",
      urlToImage: "https://s4.reutersmedia.net/resources_v2/images/rcom-default.png",
      publishedAt: "2020-03-30T07:15:00Z",
      content: "March 30 (Reuters) - Franchise Brands PLC: \r\n* FRANCHISE BRANDS PLC - BUSINESS HAS TRADED IN-LINE WITH MANAGEMENT’S EXPECTATIONS FOR Q1 AS A WHOLE \r\n* FRANCHISE BRANDS PLC - TRADING IN NEAR TERM IS LIKELY TO BE IMPACTED BY EFFECTS OF PANDEMIC \r\n* FRANCHISE BR… [+1165 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Tangi Salaün",
      title: "Five days of worship that set a virus time bomb in France",
      description: "From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: \"We're going to celebrate the Lord! Are you feeling the joy tonight?\"",
      url: "https://www.reuters.com/article/us-health-coronavirus-france-church-spec-idUSKBN21H0Q2",
      urlToImage: "https://s3.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510052791&w=1200&r=LYNXMPEG2T0EJ",
      publishedAt: "2020-03-30T07:13:39Z",
      content: "PARIS (Reuters) - From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: “We’re going to celebrate the Lord! Are you feeling the joy tonight?” \r\n“Yes!” shouted the hundreds gathered at the C… [+13011 chars]",
    },
    {
      source: {
        id: "reuters",
        name: "Reuters",
      },
      author: "Tangi Salaün",
      title: "Special Report: Five days of worship that set a virus time bomb in France",
      description: "From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: \"We're going to celebrate the Lord! Are you feeling the joy tonight?\"",
      url: "https://af.reuters.com/article/worldNews/idAFKBN21H0QJ",
      urlToImage: "https://s2.reutersmedia.net/resources/r/?m=02&d=20200330&t=2&i=1510053318&w=1200&r=LYNXMPEG2T0EI",
      publishedAt: "2020-03-30T07:07:54Z",
      content: "PARIS (Reuters) - From the stage of an evangelical superchurch, the leader of the gospel choir kicked off an evening of prayer and preaching: “We’re going to celebrate the Lord! Are you feeling the joy tonight?” \r\n“Yes!” shouted the hundreds gathered at the C… [+13015 chars]",
    },
  ],
};
