version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: rm -rf ./node_modules 
            - run: npm i
            - run: npm run build
            - run: npm run lint:check
workflows:
    build:
      jobs:
        - build
