version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: rm -rf ./node_modules 
            - run: npm i
            - run: npm run setup-all
workflows:
    build-and-test:
      jobs:
        - build-and-test
