env:
  browser: true
  es6: true
  amd: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  react/prop-types: 0
  no-unused-vars: warn
