env:
  es6: true
  node: true
  browser: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-unused-vars: 0
  no-trailing-spaces: 0
  operator-linebreak: 0
  prefer-destructuring: 0
  quotes: 0
  no-console: 0
  no-plusplus: 0
  no-nested-ternary: 0