env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
      - ".tsx"
  import/extensions: 0
  import/no-unresolved: 0
  no-unused-vars: 0
  no-trailing-spaces: 0
  operator-linebreak: 0
  prefer-destructuring: 0
  quotes: 0
  implicit-arrow-linebreak: 0


